In [ ]:
import pandas as pd
import numpy as np
from collections import Counter
import argparse
from collections import defaultdict
import math
import sys

In [ ]:
df1 = pd.read_csv('Haitian_Foods_Story.csv', header=None)
df2 = pd.read_csv('French_Foods_Story.csv',header=None)
df0 = pd.concat([df1, df2], ignore_index=True)

In [ ]:
df1

                                                     0
0    **Diri Kole ak Pwa nan Lakou Granmè Zilè**\n\n...
1    **Diri blan ak sòs pwa nan lakou Granmè Zil**\...
2    **Diri blan ak Sòs pwa nwa**\n\nTi Granmè Zilm...
3    **Diri blan ak Sòs Pwa Blan**\n\nTi Mari se yo...
4    **Diri Djondjon pou Ti Granmè**\n\nTi Granmè t...
..                                                 ...
177  **Mabi a Granmè Zilè**\n\nGranmè Zilè te gen y...
178  **Godrin Mabi ak Ananas Magik**\n\nTi Bouki te...
179  **Ti Istwa Punch**\n\nLè solèy la te kouche so...
180  **Jimex nan Mitan Nuit**\n\nTi Kako te gen yon...
181  **Juna ak Bèf Miracule**\n\nNan yon ti vilaj k...

[182 rows x 1 columns]

In [ ]:
def get_text_column(df):
    if isinstance(df, pd.Series):
        return df
    else:
        return df.iloc[:, 0]

df1 = get_text_column(df1)
df2 = get_text_column(df2)
df0 = get_text_column(df0)

In [ ]:
STOPWORDS_HT = set([
    "mwen", "ou", "li", "nou", "yo",
    "sa", "ki", "kisa",
    "nan", "sou", "ak", "pou", "pa",
    "se", "ye", "te", "ap", "pral",
    "gen", "fè", "di",
    "la", "a", "an", "lan",
    "yon", "youn",
    "men", "oswa", "paske",
    "kòm", "tankou",
    "isit", "la", "là",
    "tout", "plis", "mwens",
    "byen", "mal", "m", "ka","l", " ","t","w",
    "vin","vini","k","san","manje","moun", "si","ale","tt","sak","pi",""
])

In [ ]:
def get_log_odds(col1, col2, col0,verbose=False,lower=True):
    """Monroe et al. Fightin' Words method to identify top words in df1 and df2
    against df0 as the background corpus"""
    if lower:
        counts1 = defaultdict(int, [[i,j] for i,j in col1.str.lower().str.split(expand=True).stack().replace(r'[^a-zA-Z\s]', '', regex=True).value_counts().items()])
        counts2 = defaultdict(int,[[i,j] for i,j in col2.str.lower().str.split(expand=True).stack().replace(r'[^a-zA-Z\s]', '', regex=True).value_counts().items()])
        prior = defaultdict(int,[[i,j] for i,j in col0.str.lower().str.split(expand=True).stack().replace(r'[^a-zA-Z\s]', '', regex=True).value_counts().items()])
    else:
        counts1 = defaultdict(int,[[i,j] for i,j in col1.str.split(expand=True).stack().replace(r'[^a-zA-Z\s]', '', regex=True).value_counts().items()])
        counts2 = defaultdict(int,[[i,j] for i,j in col2.str.split(expand=True).stack().replace(r'[^a-zA-Z\s]', '', regex=True).value_counts().items()])
        prior = defaultdict(int,[[i,j] for i,j in col0.str.split(expand=True).stack().replace(r'[^a-zA-Z\s]', '', regex=True).value_counts().items()])

    sigmasquared = defaultdict(float)
    sigma = defaultdict(float)
    delta = defaultdict(float)

    for word in prior.keys():
        prior[word] = int(prior[word] + 0.5)

    for word in counts2.keys():
        counts1[word] = int(counts1[word] + 0.5)
        if prior[word] == 0:
            prior[word] = 1

    for word in counts1.keys():
        counts2[word] = int(counts2[word] + 0.5)
        if prior[word] == 0:
            prior[word] = 1

    n1 = sum(counts1.values())
    n2 = sum(counts2.values())
    nprior = sum(prior.values())

    for word in prior.keys():
        if prior[word] > 0:
            l1 = float(counts1[word] + prior[word]) / (( n1 + nprior ) - (counts1[word] + prior[word]))
            l2 = float(counts2[word] + prior[word]) / (( n2 + nprior ) - (counts2[word] + prior[word]))
            sigmasquared[word] =  1/(float(counts1[word]) + float(prior[word])) + 1/(float(counts2[word]) + float(prior[word]))
            sigma[word] =  math.sqrt(sigmasquared[word])
            delta[word] = ( math.log(l1) - math.log(l2) ) / sigma[word]

    if verbose:
        for word in sorted(delta, key=delta.get)[:10]:
            print("%s, %.3f" % (word, delta[word]))

        for word in sorted(delta, key=delta.get,reverse=True)[:10]:
            print("%s, %.3f" % (word, delta[word]))
    return delta

In [ ]:
food_results = get_log_odds(get_text_column(df1),get_text_column(df2),get_text_column(df0),verbose=False,lower=True)

In [ ]:
haitian_food_dict = defaultdict(float)
french_food_dict = defaultdict(float)
for word , score  in food_results.items():
  if score > 1.96 and word not in STOPWORDS_HT:
    haitian_food_dict[word] = food_results[word]
  if score <- 1.96  and word not in STOPWORDS_HT:
    french_food_dict[word] = food_results[word]

In [ ]:
haitian_food_dict= dict(sorted(haitian_food_dict.items(), key=lambda item: item[1], reverse=True))

In [ ]:
haitian_food_dict

{'ss': 6.287928803288579,
 'pwason': 6.208536010847571,
 'mayi': 6.178437292286819,
 'zil': 6.015282733243587,
 'klm': 5.622323127284787,
 'diri': 5.267867101057629,
 'arans': 5.110077186122919,
 'pitimi': 4.9120783725935455,
 'granm': 4.751808517715215,
 'bannann': 4.319716836482945,
 'bf': 4.247350224585178,
 'pate': 4.238215467785052,
 'janik': 4.185123423631397,
 'ragou': 4.064904152015945,
 'lam': 3.8438880390306225,
 'manyk': 3.769535202819181,
 'tablt': 3.769535202819181,
 'labouyi': 3.725431178558025,
 'griyo': 3.6598452458852053,
 'taso': 3.6356204991837413,
 'jimex': 3.4965873505427125,
 'klmns': 3.4965873505427125,
 'ji': 3.4965873505427125,
 'kabrit': 3.468697948791899,
 'tibo': 3.3606398211696495,
 'bouyon': 3.3564729819385435,
 'pwa': 3.279260149864997,
 'kaka': 3.2535490266798845,
 'espageti': 3.2516974450966107,
 'e': 3.242855439880214,
 'malta': 3.200474060701258,
 'patat': 3.1690580816989535,
 'by': 3.1484182144493076,
 'ze': 3.113088812981295,
 'ble': 3.098434108750575,
 'kole': 3.095487908863558,
 'lanbi': 3.095487908863558,
 'mari': 3.081793456397962,
 'moulen': 2.974738283899124,
 'boukannen': 2.930972606743724,
 'kouskous': 2.930972606743724,
 'tijoel': 2.874044008948983,
 'kasav': 2.866076987669582,
 'mabi': 2.8159656620427427,
 'zaboka': 2.7776355744010144,
 'kd': 2.7646455351995027,
 'aransl': 2.756664897058749,
 'bonbon': 2.7309462483540985,
 'jezi': 2.696061052702796,
 'zaka': 2.696061052702796,
 'marilz': 2.696061052702796,
 'bty': 2.696061052702796,
 'pye': 2.6090090850394922,
 'pdi': 2.583659991329146,
 'tonm': 2.570573514032523,
 'pistach': 2.570573514032523,
 'fresko': 2.5298246156610475,
 'fil': 2.505475471199655,
 'tritri': 2.505475471199655,
 'salz': 2.4386413394572273,
 'yanm': 2.4386413394572273,
 'kzna': 2.4386413394572273,
 'chanm': 2.406958890726601,
 'pen': 2.3982793803630997,
 'bw': 2.396535507542685,
 'lamy': 2.396535507542685,
 'danyl': 2.369924245231129,
 'lm': 2.353278203340206,
 'chache': 2.3452480210039597,
 'chiko': 2.3271015784428557,
 'toro': 2.299155360902325,
 'kawol': 2.299155360902325,
 'andwi': 2.299155360902325,
 'kremas': 2.299155360902325,
 'kalalou': 2.276811751374098,
 'pwasong': 2.2555910308855753,
 'mousa': 2.2261390160350496,
 'mam': 2.2261390160350496,
 'kokiyl': 2.2261390160350496,
 'jeanson': 2.2261390160350496,
 'klmt': 2.2261390160350496,
 'lmm': 2.2261390160350496,
 'salix': 2.2261390160350496,
 'viv': 2.2202936167985494,
 'ank': 2.2052916020435913,
 'bwe': 2.177522641926411,
 'boukla': 2.150646312968777,
 'lik': 2.150646312968777,
 'tchous': 2.150646312968777,
 'mzil': 2.150646312968777,
 'fanm': 2.0946446449815097,
 'tito': 2.0724066463397093,
 'kola': 2.0724066463397093,
 'frikase': 2.0724066463397093,
 'sapibon': 2.0724066463397093,
 'vw': 2.0724066463397093,
 'miren': 2.0724066463397093,
 'konparet': 2.0724066463397093,
 'manba': 2.0696761224829117,
 'kongo': 2.0687096019350193,
 'man': 2.0575922151139276,
 'kokoye': 2.0381372633510346,
 'kochon': 2.0371568300351988,
 'dous': 2.0310481957062225,
 'bouden': 1.9910962185547274,
 'tati': 1.9910962185547274,
 'pendou': 1.9910962185547274,
 'punch': 1.9910962185547274,
 'ananas': 1.9910962185547274,
 'tris': 1.9884952520498425,
 'lakay': 1.9793427961698593,
 'vij': 1.975074183759541}

In [ ]:
french_food_dict = dict(sorted(french_food_dict.items(), key=lambda item: item[1]))

In [ ]:
french_food_dict

{'marilne': -6.4715999373153235,
 'fromaj': -6.4559864014383095,
 'lili': -6.111390145919218,
 'tante': -5.783708005372103,
 'soupe': -5.368081637221219,
 'pain': -4.984849042862058,
 'tarte': -4.858554930242061,
 'manmi': -4.673487838921151,
 'mariln': -4.5616573043308355,
 'lizt': -4.184522387154441,
 'plat': -4.097079797408957,
 'epui': -4.01930987013629,
 'moso': -4.013896118329931,
 'zaza': -3.860771222155983,
 'mz': -3.501748787903641,
 'ufs': -3.479931435965474,
 'restoran': -3.458147917630464,
 'gat': -3.38950202797054,
 'tijo': -3.3786778626792096,
 'maris': -3.3331150426959626,
 'vani': -3.287632484649155,
 'monsy': -3.258253815740643,
 'graten': -3.249147842947387,
 'mireille': -3.2009973211764455,
 'bouch': -3.048393262407174,
 'fonn': -3.02991683068681,
 'boudin': -3.0006866389812306,
 'le': -3.0006866389812306,
 'madanm': -2.9568915466649752,
 'souvenans': -2.9267355667798576,
 'lodie': -2.8412097623964567,
 'fmaj': -2.8412097623964567,
 'baba': -2.8412097623964567,
 'fmen': -2.8353479895877256,
 'gate': -2.786024651310748,
 'salad': -2.765043418321764,
 'epym': -2.739820391400396,
 'de': -2.6882042677736724,
 'koko': -2.688010728977149,
 'gaufres': -2.6722403720701813,
 'jacques': -2.6722403720701813,
 'boulanj': -2.6722403720701813,
 'kok': -2.6722403720701813,
 'aux': -2.6722403720701813,
 'chez': -2.652026147311361,
 'rest': -2.652026147311361,
 'madame': -2.627176020627944,
 'eskago': -2.6134925694533484,
 'pn': -2.5937637915450087,
 'marz': -2.5533944077993453,
 'marie': -2.5434515745679547,
 'portauprince': -2.5068584694900213,
 'lapin': -2.4918481855072794,
 'jambon': -2.4918481855072794,
 'morue': -2.4918481855072794,
 'krem': -2.4918481855072794,
 'palmi': -2.428743820168687,
 'beign': -2.428743820168687,
 'tzf': -2.411032776715371,
 'it': -2.3639565340485547,
 'poulet': -2.3639565340485547,
 'morso': -2.3579084598761013,
 'pralin': -2.297343951636441,
 'mariela': -2.297343951636441,
 'kob': -2.281636119711274,
 'sonje': -2.2554150863386697,
 'au': -2.2287424157294464,
 'chouket': -2.2287424157294464,
 'dami': -2.2287424157294464,
 'lmk': -2.2287424157294464,
 'glaces': -2.2287424157294464,
 'fraiz': -2.2287424157294464,
 'jean': -2.2287424157294464,
 'thrse': -2.2287424157294464,
 'nougat': -2.2287424157294464,
 'choux': -2.2287424157294464,
 'pounti': -2.2287424157294464,
 'papye': -2.2254735867050806,
 'km': -2.2040836150290777,
 'jus': -2.193016726929499,
 'mesye': -2.172108473338118,
 'camembert': -2.157962248381258,
 'jeannot': -2.157962248381258,
 'fwomaj': -2.157962248381258,
 'charlotte': -2.157962248381258,
 'klmz': -2.157962248381258,
 'tz': -2.157962248381258,
 'ratatouille': -2.157962248381258,
 'velout': -2.157962248381258,
 'grizo': -2.157962248381258,
 'daniel': -2.157962248381258,
 'gou': -2.1167302027903223,
 'chv': -2.1061519097825747,
 'mouton': -2.084781562019595,
 'comt': -2.084781562019595,
 'galt': -2.084781562019595,
 'tanti': -2.084781562019595,
 'bagt': -2.084781562019595,
 'brioch': -2.084781562019595,
 'marisl': -2.084781562019595,
 'un': -2.084781562019595,
 'langoust': -2.084781562019595,
 'nwaj': -2.0658506168840987,
 'jn': -2.0642440424589497,
 'ane': -2.0555147543738213,
 'klod': -2.0555147543738213,
 'lte': -2.0319552211807204,
 'kout': -2.027972221931193,
 'saumon': -2.008938038686353,
 'tropzienne': -2.008938038686353,
 'mzilia': -2.008938038686353,
 'croissant': -2.008938038686353,
 'magret': -2.008938038686353,
 'pomdete': -2.008938038686353,
 'rosalie': -2.008938038686353,
 'rhum': -2.008938038686353,
 'ska': -2.008938038686353,
 'une': -2.008938038686353,
 'tomat': -2.000025549338899,
 'des': -2.000025549338899,
 'tap': -1.988088929414784,
 'kado': -1.981582517356344}

Artist

In [ ]:
df_haitian = pd.read_csv('Haitian_Musical_Groups_Story.csv', header=None)
df_french = pd.read_csv('French_Artists_Story.csv',header=None)
df_all = pd.concat([df_haitian, df_french], ignore_index=True)

In [ ]:
df_haitian

                                                     0
0    **Lè Mizik Tabou Combo Te Fè Kè Jean-Pierre Ba...
1    **Lè Mizik T-Vice Te Fè Kè Roberto Bat Tanbou ...
2    **Ti Istwa a**\n\n*Lè sol la te kouche sou Por...
3    **Ti Istwa a : "Mizik Nu-look nan Kè Mwen"**\n...
4    **Lè Mizik Harmonik a Te Fè Kè Li Chante**\n\n...
..                                                 ...
193  **Ti Mizik ki Te Fè Kè Li Klere**\n\nLè solèy ...
194  **Lè Gazzman Te Fè Kè Li Pale**\n\nTi Gwo Wozo...
195  **Ti Istwa a : "Mizik ki te fè lè l vin nwa"**...
196  **Lè Mizik an Te Fè Lavi Li Klere**\n\nTi Klod...
197  **Lè Mizik Toby Anbakè Te Fè Kè Jean-Bob Bat P...

[198 rows x 1 columns]

In [ ]:
artist_results = get_log_odds(get_text_column(df_haitian),get_text_column(df_french),get_text_column(df_all),verbose=False,lower=True)

In [ ]:
haitian_artist_dict = {}
french_artist_dict = {}
for word , score  in artist_results.items():
  if score > 1.96 and word not in STOPWORDS_HT:
    haitian_artist_dict[word] = artist_results[word]
  if score <- 1.96 and word not in STOPWORDS_HT:
    french_artist_dict[word] = artist_results[word]

In [ ]:
haitian_artist_dict = dict(sorted(haitian_artist_dict.items(), key=lambda item: item[1], reverse=True))

In [ ]:
haitian_artist_dict

{'bouki': 4.691559581908997,
 'mesye': 4.038493057866309,
 'kako': 3.897993610661615,
 'tanbou': 3.8481557064471605,
 'rozo': 3.784550535734445,
 'gwo': 3.688296334469279,
 'kaka': 3.601756165501541,
 'jilo': 3.4420534335105244,
 'obas': 3.4132035204417797,
 'gabel': 3.2179511238144474,
 'bwa': 3.2098812646453005,
 'yole': 3.11574453274719,
 'jj': 3.06560511257279,
 'man': 3.0556788608364047,
 'manti': 2.982581819931784,
 'jo': 2.9039351450977167,
 'wozo': 2.8980686784319234,
 'josu': 2.708088864928788,
 'gita': 2.6403653872750956,
 'zenglen': 2.6067313900188975,
 'alex': 2.5438998646719835,
 'bat': 2.523165361804259,
 'ginen': 2.481815149357855,
 'tijack': 2.479477632808562,
 'emisyon': 2.4357832897329637,
 'mak': 2.413337309616308,
 'richardo': 2.413337309616308,
 'toby': 2.413337309616308,
 'jakito': 2.413337309616308,
 'durosier': 2.413337309616308,
 'chante': 2.364543852997718,
 'jc': 2.3453335448415986,
 'gwozo': 2.3453335448415986,
 'drose': 2.3453335448415986,
 'guy': 2.3453335448415986,
 'choucoune': 2.3453335448415986,
 'jeanpierre': 2.301669522159742,
 'disip': 2.2752992619069583,
 'wesly': 2.2752992619069583,
 'manno': 2.2752992619069583,
 'ralph': 2.2752992619069583,
 'belo': 2.203040819850618,
 'jim': 2.203040819850618,
 'big': 2.203040819850618,
 'ansy': 2.203040819850618,
 'baky': 2.203040819850618,
 'kato': 2.203040819850618,
 'tijoze': 2.203040819850618,
 'toto': 2.203040819850618,
 'cave': 2.1283316951446496,
 'zatrap': 2.1283316951446496,
 'kbert': 2.1283316951446496,
 'roberto': 2.1283316951446496,
 'tijozf': 2.1283316951446496,
 'tonton': 2.111515767548073,
 'granmoun': 2.093704045931512,
 'rasin': 2.086487185388546,
 'repnn': 2.0659418305846917,
 'dadou': 2.0509040891857437,
 'niko': 2.0509040891857437,
 'tifane': 2.0509040891857437,
 'tafa': 2.0509040891857437,
 'gardy': 2.0509040891857437,
 'dieudonn': 2.0509040891857437,
 'jackito': 2.0509040891857437,
 'josy': 2.0509040891857437,
 'kenny': 2.0509040891857437,
 'wanito': 2.0509040891857437,
 'toussaint': 2.0509040891857437,
 'alan': 2.0509040891857437,
 'chanre': 2.0509040891857437,
 'micky': 2.039306101393322,
 'don': 2.0022937240819156,
 'konpa': 1.9867438090698495,
 'enstriman': 1.984803408418642,
 'liw': 1.9704375629005204,
 'marjory': 1.9704375629005204,
 'josiane': 1.9704375629005204,
 'michael': 1.9704375629005204,
 'fatima': 1.9704375629005204,
 'fabre': 1.9704375629005204,
 'darline': 1.9704375629005204,
 'wendyyy': 1.9704375629005204,
 'lunet': 1.9704375629005204,
 'klodis': 1.9654852660666708,
 'mt': 1.9643103537792224,
 'black': 1.9633885638424153}

In [ ]:
french_artist_dict = dict(sorted(french_artist_dict.items(), key=lambda item: item[1]))

In [ ]:
french_artist_dict

{'jasmin': -5.028735442922997,
 'jai': -4.3990593460945195,
 'le': -4.312659636486192,
 'frans': -4.138857237501735,
 'jude': -4.046745621488514,
 'les': -4.045380098887226,
 'dany': -3.9020647180284507,
 'et': -3.778115651193731,
 'jeanmax': -3.6499656542623207,
 'klmn': -3.5171555655075513,
 'paris': -3.4257597107486584,
 'mireille': -3.4187121153494373,
 'des': -3.3681348125562214,
 'on': -3.197738766468933,
 'franse': -3.1858324207260678,
 'un': -3.084645973391216,
 'portauprince': -3.0655441784788895,
 'suis': -3.0327881829050445,
 'rap': -3.0307236332240337,
 'djo': -2.9108259538752623,
 'manouchka': -2.89671421242841,
 'me': -2.8672251247718203,
 'pas': -2.85398463718101,
 'radio': -2.8470155704765445,
 'jeanphilippe': -2.815831138286122,
 'lara': -2.758929509105151,
 'une': -2.758929509105151,
 'que': -2.758929509105151,
 'diski': -2.758929509105151,
 'tu': -2.758929509105151,
 'lodie': -2.758929509105151,
 'tijol': -2.700830206430633,
 'mzilz': -2.700830206430633,
 'mwa': -2.645108005580834,
 'cest': -2.6414542022399603,
 'ekri': -2.608786971900042,
 'kafe': -2.58332449516126,
 'vie': -2.5363537844738184,
 'mlodie': -2.5185089818679485,
 'rv': -2.5088507355008103,
 'chof': -2.5081650085543603,
 'taptap': -2.5081650085543603,
 'marieclaire': -2.4858190927540567,
 'klodine': -2.4547297574767803,
 'valiz': -2.441965674473916,
 'en': -2.420606098103892,
 'mariejose': -2.4048422963591958,
 'ma': -2.3892495899789785,
 'qui': -2.3425838684788274,
 'jn': -2.341041739137572,
 'cali': -2.3219245798660717,
 'klervil': -2.3219245798660717,
 'moi': -2.3219245798660717,
 'malice': -2.3219245798660717,
 'du': -2.311394559905901,
 'ne': -2.274423058202722,
 'pour': -2.274423058202722,
 'biy': -2.2657691760423084,
 'agar': -2.252589318157015,
 'fifo': -2.252589318157015,
 'taime': -2.252589318157015,
 'mon': -2.252589318157015,
 'jeanclair': -2.2090465219032347,
 'lose': -2.1810520966267246,
 'the': -2.1810520966267246,
 'lavil': -2.1620012118409915,
 'lzm': -2.1196400876516113,
 'clara': -2.1070886526862203,
 'rue': -2.0845678316597547,
 'panse': -2.0611946040867855,
 'lami': -2.0568743439356885,
 'rohff': -2.0304338606394605,
 'renaud': -2.0304338606394605,
 'eddy': -2.0304338606394605,
 'brigitte': -2.0304338606394605,
 'bourvil': -2.0304338606394605,
 'vald': -2.0304338606394605,
 'zola': -2.0304338606394605,
 'ninho': -2.0304338606394605,
 'sinclar': -2.0304338606394605,
 'gaby': -2.0304338606394605,
 'kenson': -1.999069652837804,
 'bar': -1.9819430048142137,
 'bwe': -1.9784373706780836,
 'voyaje': -1.9633967487948492}

In [ ]:
df_haitian_person = pd.read_csv('Haitian_people_names_stories.csv', header=None)
df_french_person = pd.read_csv('French_people_name_stories.csv',header=None)
df_all_person = pd.concat([df_haitian_person, df_french_person], ignore_index=True)

In [ ]:
df_haitian_person

                                                     0
0    **Colette ak Chèz la**\n\nPort-au-Prince, nan ...
1    **Wilson ak Chwal Bwa**\n\nWilson te gen yon t...
2    **Albert ak Bwa Mango**\n\nAlbert te gen yon t...
3    **Anthony ak Bwa Mango**\n\nAnthony te gen yon...
4    **Anderson ak Chèz la**\n\nAnderson te gen yon...
..                                                 ...
145  **Magloire ak Chwal Bò Kòd**\n\nMagloire te ge...
146  **Maxime ak Chèz la nan Lavil**\n\nMaxime te g...
147  **Jean-Baptiste ak Chwal Bòkò**\n\nJean-Baptis...
148  **Tamzin ak Chèz la nan Vilaj La**\n\nVilaj La...
149  **Leonel ak Chèz la**\n\nLeonel te gen yon ti ...

[150 rows x 1 columns]

In [ ]:
person_results = get_log_odds(get_text_column(df_haitian_person),get_text_column(df_french_person),get_text_column(df_all_person),verbose=False,lower=True)

In [ ]:
haitian_person_dict = defaultdict(float)
french_person_dict = defaultdict(float)
for word , score  in person_results.items():
  if score > 1.96 and word not in STOPWORDS_HT:
    haitian_person_dict[word] = person_results[word]
  if score < -1.96  and word not in STOPWORDS_HT:
    french_person_dict[word] = person_results[word]

In [ ]:
haitian_person_dict = dict(sorted(haitian_person_dict.items(), key=lambda item: item[1], reverse=True))

In [ ]:
haitian_person_dict

{'chwal': 8.395173912615796,
 'bwa': 5.921806523837485,
 'mango': 5.908805724011857,
 'tap': 5.436088872174385,
 '': 5.156656154078175,
 'dlo': 4.919106731980272,
 'granm': 4.053057354424284,
 'lajan': 3.9698820691306587,
 'bt': 3.9243762074770054,
 'machann': 3.642304902463652,
 'mang': 3.4916802903747324,
 'mn': 3.4035693008332695,
 'kd': 3.2652090626944346,
 'lakay': 3.2644922127061706,
 'kouri': 3.1888486586233533,
 'koupe': 3.123983587031235,
 'ank': 3.070488277481679,
 'zn': 2.998323858956178,
 'arnold': 2.9600001274555794,
 'monte': 2.9196621307912265,
 'edris': 2.906649945939278,
 'monsy': 2.8578481337839112,
 'eloi': 2.8523030055914527,
 'vann': 2.8323812363917167,
 'msye': 2.775419808113132,
 'dadi': 2.740380559628676,
 'zwazo': 2.7403198699315383,
 'va': 2.7170041897020374,
 'mapou': 2.7122962744400216,
 'pran': 2.6918088556169066,
 'nwit': 2.6910409943603457,
 'gason': 2.6875222020451313,
 'wilson': 2.682670359881246,
 'jude': 2.682670359881246,
 'magloire': 2.682670359881246,
 'josu': 2.682670359881246,
 'okip': 2.664126270614868,
 'bay': 2.6460688086725783,
 'benito': 2.623692108716155,
 'burton': 2.623692108716155,
 'lesly': 2.623692108716155,
 'macht': 2.623692108716155,
 'fabrice': 2.623692108716155,
 'daniel': 2.623692108716155,
 'clment': 2.623692108716155,
 'ren': 2.623692108716155,
 'val': 2.5971322745630583,
 'goud': 2.578459741140718,
 'oreste': 2.5633582808781386,
 'frantz': 2.5633582808781386,
 'ignace': 2.5633582808781386,
 'hector': 2.5633582808781386,
 'horace': 2.5633582808781386,
 'raoul': 2.5633582808781386,
 'mario': 2.5633582808781386,
 'man': 2.5505317296914933,
 'galri': 2.546531617372128,
 'mayi': 2.5425400858755176,
 'pami': 2.5224691640995305,
 'marilne': 2.5015707953404354,
 'antonio': 2.5015707953404354,
 'jacqueline': 2.5015707953404354,
 'lee': 2.5015707953404354,
 'borno': 2.5015707953404354,
 'chibly': 2.5015707953404354,
 'hubert': 2.5015707953404354,
 'mizl': 2.5015707953404354,
 'lalin': 2.4980178000272817,
 'anba': 2.4948860777222452,
 'boutik': 2.4885804359363797,
 'pitit': 2.4671756883787985,
 'achte': 2.4525451926784028,
 'tancrde': 2.438219142139173,
 'dudley': 2.438219142139173,
 'abner': 2.438219142139173,
 'bruno': 2.438219142139173,
 'etzer': 2.438219142139173,
 'eduard': 2.438219142139173,
 'gerald': 2.438219142139173,
 'dants': 2.438219142139173,
 'barbara': 2.438219142139173,
 'chwa': 2.437608298286207,
 'mt': 2.4343184454720284,
 'bdlanm': 2.425064310258123,
 'bouki': 2.3909088279630333,
 'anthony': 2.3731780588529765,
 'jeff': 2.3731780588529765,
 'clotilde': 2.3731780588529765,
 'liliane': 2.3731780588529765,
 'mariethrse': 2.3731780588529765,
 'leonel': 2.3731780588529765,
 'adelina': 2.3731780588529765,
 'joel': 2.3731780588529765,
 'tzil': 2.3063046168656127,
 'charlemagne': 2.3063046168656127,
 'gary': 2.3063046168656127,
 'johnny': 2.3063046168656127,
 'fernand': 2.3063046168656127,
 'lanm': 2.2907497854245493,
 'branch': 2.2867744975352626,
 'ba': 2.2687390432744725,
 'alix': 2.2374345231203465,
 'elza': 2.2374345231203465,
 'flix': 2.2374345231203465,
 'jimmy': 2.2374345231203465,
 'hrard': 2.2374345231203465,
 'joachim': 2.2374345231203465,
 'tamzin': 2.2374345231203465,
 'bf': 2.2249459970926986,
 'pye': 2.2145583231868358,
 'pyebwa': 2.1753038453674542,
 'osvaldo': 2.1663773626356275,
 'anderson': 2.1663773626356275,
 'jeaneudes': 2.1663773626356275,
 'marvin': 2.1663773626356275,
 'romain': 2.1663773626356275,
 'oliver': 2.1663773626356275,
 'manno': 2.1663773626356275,
 'gontran': 2.1663773626356275,
 'maxime': 2.1663773626356275,
 'william': 2.1663773626356275,
 'oswald': 2.1663773626356275,
 'alan': 2.1663773626356275,
 'mi': 2.115491481171533,
 'yvesmarie': 2.0929103855486053,
 'fabien': 2.0929103855486053,
 'florine': 2.0929103855486053,
 'ludovic': 2.0929103855486053,
 'lionel': 2.0929103855486053,
 'jackson': 2.0929103855486053,
 'ida': 2.0929103855486053,
 'benot': 2.0929103855486053,
 'nadine': 2.0929103855486053,
 'kevin': 2.0929103855486053,
 'ajoupe': 2.083862535097959,
 'frwi': 2.063549827930294,
 'remd': 2.060971893276324,
 'leroy': 2.0558543240385676,
 'gwo': 2.035486879506514,
 'luck': 2.016770254375939,
 'dofen': 2.016770254375939,
 'fred': 2.016770254375939,
 'max': 2.016770254375939,
 'alrich': 2.016770254375939,
 'dieudonn': 2.016770254375939,
 'ernst': 2.016770254375939,
 'ange': 2.016770254375939,
 'windsor': 2.016770254375939,
 'jiska': 2.004487671180831,
 'desann': 1.9671339772945982}

In [ ]:
french_person_dict = dict(sorted(french_person_dict.items(), key=lambda item: item[1]))

In [ ]:
french_person_dict

{'frans': -8.908483665856023,
 'vilaj': -5.541926711398781,
 'mari': -5.441499248510679,
 'roche': -5.373349124682374,
 'claire': -5.012796441086835,
 'kle': -4.9351112253852945,
 'lodie': -4.925931605193525,
 'paris': -4.473199292784024,
 'vizaj': -4.074768096714514,
 'marie': -3.7144535000892422,
 'ekri': -3.6517262235708348,
 'gri': -3.6446161570596187,
 'liv': -3.644268006624797,
 'peyi': -3.5695490152089655,
 'aprann': -3.5530628629507914,
 'tren': -3.4834485758703995,
 'kreyl': -3.4304969440923205,
 'marcel': -3.3879643490603075,
 'kafe': -3.330456722994838,
 'restoran': -3.299488829701659,
 'renmen': -3.292746518711081,
 'pandan': -3.2590526835988336,
 'fi': -3.219216845735961,
 'valiz': -3.164957993980338,
 'foto': -3.1562861492661685,
 'dubois': -3.0871355439033694,
 'hlose': -3.083845502645026,
 'kote': -3.0769685903092485,
 'madame': -3.066625392850505,
 'lyon': -3.00824372836839,
 'zy': -2.9868400283468786,
 'lavi': -2.9652777540150845,
 'souri': -2.926023201544804,
 'claudette': -2.919945121777204,
 'atelye': -2.8572535569442383,
 'karim': -2.8053684223586544,
 'bertille': -2.8053684223586544,
 'pen': -2.800399368173545,
 'de': -2.7994503233403973,
 'madanm': -2.790535715391344,
 'lag': -2.766296938755807,
 'hlne': -2.746289619761776,
 'mouha': -2.746289619761776,
 'sophie': -2.746289619761776,
 'rmy': -2.746289619761776,
 'lt': -2.6939420867006874,
 'jeanne': -2.6859126945125045,
 'gaston': -2.6859126945125045,
 'esprit': -2.6859126945125045,
 'pierrette': -2.6859126945125045,
 'florian': -2.6241480457191617,
 'yassine': -2.6241480457191617,
 'boris': -2.6241480457191617,
 'rmi': -2.6241480457191617,
 'btran': -2.6241480457191617,
 'csar': -2.5608952663910483,
 'istwa': -2.551696932727832,
 'jeanluc': -2.524375575408309,
 'theobald': -2.496041225851186,
 'lodewijk': -2.496041225851186,
 'foulques': -2.496041225851186,
 'lane': -2.496041225851186,
 'henriette': -2.429457691114127,
 'marieanne': -2.429457691114127,
 'patrice': -2.429457691114127,
 'patwon': -2.429457691114127,
 'david': -2.429457691114127,
 'matteo': -2.429457691114127,
 'soti': -2.417109576944853,
 'avyon': -2.3865052692499544,
 'ri': -2.378882227284224,
 'istvn': -2.360998344050014,
 'albric': -2.360998344050014,
 'rodolphe': -2.360998344050014,
 'lumi': -2.360998344050014,
 'resi': -2.344470425206472,
 'fent': -2.344470425206472,
 'lang': -2.336523574652491,
 'odo': -2.290494995435848,
 'adolphe': -2.290494995435848,
 'muguette': -2.290494995435848,
 'bernard': -2.290494995435848,
 'aksan': -2.2327334195577637,
 'jeanalain': -2.217752714648547,
 'napoleon': -2.217752714648547,
 'trantcinq': -2.217752714648547,
 'mathieu': -2.217752714648547,
 'jos': -2.217752714648547,
 'george': -2.217752714648547,
 'igor': -2.217752714648547,
 'gautier': -2.217752714648547,
 'napolon': -2.217752714648547,
 'des': -2.217752714648547,
 'gustave': -2.217752714648547,
 'boulanjri': -2.217752714648547,
 'giuseppe': -2.217752714648547,
 'kaf': -2.197008951578173,
 'batoch': -2.142543469369516,
 'piyano': -2.142543469369516,
 'bibliyotk': -2.142543469369516,
 'steed': -2.142543469369516,
 'franoisnol': -2.142543469369516,
 'grgory': -2.142543469369516,
 'conon': -2.142543469369516,
 'athanase': -2.142543469369516,
 'eugne': -2.142543469369516,
 'gilles': -2.142543469369516,
 'mahieu': -2.142543469369516,
 'thibaud': -2.142543469369516,
 'johan': -2.142543469369516,
 'timothy': -2.142543469369516,
 'premye': -2.1373742243547165,
 'konprann': -2.128391041962001,
 'mizik': -2.0983592991818667,
 'ferm': -2.0964825560498963,
 'espesyal': -2.085377296833034,
 'repare': -2.076514074628616,
 'arlette': -2.0645976771336465,
 'marine': -2.0645976771336465,
 'jeanmarc': -2.0645976771336465,
 'meday': -2.0645976771336465,
 'vilfredo': -2.0645976771336465,
 'douard': -2.0645976771336465,
 'hugo': -2.0645976771336465,
 'tas': -2.0253964082526466,
 'santi': -2.021716119682523,
 'viye': -1.9947908076167713,
 'gal': -1.9835927641736804,
 'edmund': -1.9835927641736804,
 'arnaut': -1.9835927641736804,
 'henri': -1.9835927641736804,
 'pascale': -1.9835927641736804,
 'franz': -1.9835927641736804,
 'loue': -1.9835927641736804,
 'lloyd': -1.9835927641736804,
 'charlesdouard': -1.9835927641736804,
 'baftimbi': -1.9835927641736804,
 'christiane': -1.9835927641736804,
 'irne': -1.9835927641736804,
 'samuel': -1.9835927641736804,
 'jeanpaul': -1.9835927641736804,
 'alfred': -1.9835927641736804,
 'anna': -1.9835927641736804,
 'luigi': -1.9835927641736804,
 'achille': -1.9835927641736804,
 'mistik': -1.980163693993616,
 'montre': -1.977960460084661,
 'pale': -1.9765358666094288}